input :
    map_size: 1024 # 32*32
    map_w : 32
    map_h : 32
    feature_w: 32 # feature_w = round(map_w / spatial_w)
    feature_h: 32 # feature_h = round(map_h / spatial_h)
    feature_t : 48 # feature_t = round(time_cutoff / temporal)
network :
    num_heads : 2
    feed_forward_factor : 4 # d_model, n_head, feedforward_factor // self.dim_feedforward = feedforward_factor * d_model
    sub_num_heads : 2
    sub_feed_forward_factor : 4 # d_model, n_head, feedforward_factor // self.dim_feedforward = feedforward_factor * d_model
    sub_layers : 3
    subset_agent_max : 50
    in_channels : [16, 16, 32, 64]
    out_channels : [16, 32, 64, 128]
